---
- hosts: all
  become: yes

  tasks:
    - name: Add Docker repo
      get_url:
          url: https://download.docker.com/linux/centos/docker-ce.repo
          dest: /etc/yum.repos.d/docer-ce.repo
      become: yes

    - name: Enable Docker repo
      ini_file:
          dest: /etc/yum.repos.d/docer-ce.repo
          section: 'docker-ce-edge'
          option: enabled
          value: '0'
      become: yes

    - name: Install Docker
      package:
       name: docker-ce
       state: latest
      become: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Open Firewall Port (jenkins and wordpress)
      firewalld:
          zone: public
          port: 8080/tcp
          permanent: true
          state: enabled
          immediate: true

    - name: sudo without password for wheel group
      copy:
           content: '%wheel ALL=(ALL:ALL) NOPASSWD:ALL'
           dest: /etc/sudoers.d/wheel_nopasswd
           mode: 0440

- hosts: workers
  become: yes

  tasks:
    - name: User add Jenkins at workers
      user:
           name: jenkins
           comment: "Jenkins System"

    - name: User Jenkins add group Docker and change Shell
      user:
           name: jenkins
           shell: /bin/bash
           groups: docker,wheel
           append: yes

    - name: Set authorized key took from file
      authorized_key:
                user: jenkins
                state: present
                key: "{{ lookup('file', 'id_rsa.pub') }}"


- hosts: master
  become: yes

  tasks:
    - name: Ensure Jenkins Repository is Installed
      yum_repository:
       name: jenkins
       state: present
       description: Official Jenkins Yum Repo
       baseurl: https://pkg.jenkins.io/redhat-stable
       gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
       gpgcheck: yes
       enabled: yes

    - name: Installed JDK
      yum :
          name: java-1.8.0-openjdk
          update_cache: yes
          state: present

    - name: Installed Git
      yum :
          name: git
          update_cache: yes
          state: present

    - name: Ensure Jenkins is Installed
      yum :
          name: jenkins
          update_cache: yes
          state: present

    - name: Add user jenkins to docker group
      user:
       name: jenkins
       groups: docker
       append: yes
      become: yes

    - name: Jankins user change shell and home dir
      user:
       name: jenkins
       home: /home/jenkins
       shell: /bin/bash

    - name: Creates directory
      file:
           path: /home/jenkins/.ssh
           state: directory
           owner: jenkins
           group: jenkins
           mode: 0700

    - name: Install ssh key priv
      copy:
            src: "/root/ansible/id_rsa"
            dest: "/home/jenkins/.ssh/id_rsa"
            mode: 0600
            owner: jenkins

    - name: Enable and Start the Jenkins Service
      service:
          name: jenkins
          enabled: yes
          state: started
...